spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver 
    hikari.pool-name: INNODBMYSQL-Pool
    name: INNODBMYSQL
    type: com.zaxxer.hikari.HikariDataSource
 

management:
  health:
    diskspace.enabled: false
    db.enabled: true
  endpoints:
    web:
      base-path: / 
      exposure:
        include: '*'
        exclude: shutdown
  endpoint:
    health:
      show-details: always
     
info:
  groupId: '@project.groupId@'
  artifactId: '@project.artifactId@'
  description: '@project.description@'  
  version: '@project.version@'