spring:
  application:
    name: qa-api
  datasource:
    url: jdbc:mysql://testdatabase.cbda90k3dzzk.us-east-2.rds.amazonaws.com:3306/innodb
    username: admin  
    password: testpassword
    
server:
  port: 5000
  
hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000           
                      
config:
  example-url: 